# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: funtoo:latest

before_script:
  - echo "Before script section"
  - ego sync
  - echo 'ACCEPT_KEYWORDS="**"' >> /etc/portage/make.conf
   
after_script:
  - echo "After script section"
  - echo "Listing enabled settings"
  - ego profile
  - ego kit

build:
  stage: build
  script:
    - echo "Do your build here"
    - cd /builds/liguros/kit-fixups
    - git diff --name-only "HEAD..HEAD^"
    - for i in $(git diff --name-only "HEAD..HEAD^"|grep ebuild|awk -F "/" '{print $NF}' |rev | cut -f 2- -d '.'|rev); do echo $i; emerge -v1 "=$i"; done
    - echo "All ebuilds processed!"
